stages:
 - build

Ubuntu-Optional-Deps:
 stage: build
 script:
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON -DVISIMPL_OPTIONALS_AS_REQUIRED=ON"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Ninja"
  - bash .gitlab-ci.sh
 except:
  - master
 tags:
  - ubuntu

Ubuntu-Optional-Deps-master:
 stage: build
 script:
  - export APPIMAGES="visimpl stackviz"
  - export APPIMAGE_REPO="gitlabci@gmrv.es:apps.private"
  - export APPIMAGE_ICON="visimpl/icons/visimpl-icon-square.png"
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON -DVISIMPL_OPTIONALS_AS_REQUIRED=ON"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export GITHUB_MIRROR_URL="git@github.com:vg-lab/visimpl"
  - export BUILD_GENERATOR="Ninja"
  - bash .gitlab-ci.sh
 only:
  - master
 tags:
  - ubuntu

Ubuntu-Subproject:
 stage: build
 script:
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - export BUILD_GENERATOR="Ninja";
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

OSX-Optional-Deps-master:
 stage: build
 script:
  - export APPBUNDLES="visimpl stackviz"
  - export DMGAPP_REPO="gitlabci@gmrv.es:apps.private"
  - module load Qt-5.9.1
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON -DVISIMPL_OPTIONALS_AS_REQUIRED=ON -DGLUT_glut_LIBRARY=/usr/local/Cellar/freeglut/3.0.0/lib/libglut.dylib"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Ninja"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 only:
  - master
 tags:
  - osx-sierra

OSX-Optional-Deps:
 stage: build
 script:
  - module load Qt-5.9.1
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON -DVISIMPL_OPTIONALS_AS_REQUIRED=ON -DGLUT_glut_LIBRARY=/usr/local/Cellar/freeglut/3.0.0/lib/libglut.dylib"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Ninja"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 except:
  - master
 tags:
  - osx-sierra

OSX-Subproject:
 stage: build
 script:
  - module load Qt-5.9.1
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON -DGLUT_glut_LIBRARY=/usr/local/Cellar/freeglut/3.0.0/lib/libglut.dylib"
  - export BUILD_GENERATOR="Ninja";
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx-sierra

# Win7:
#  stage: build
#   script:
#   - call %ENVFILESDIR%\Bonjour-SDK.bat
#   - call %ENVFILESDIR%\Boost-1.72-vs14-x64.bat
#   - call %ENVFILESDIR%\Qt-5.12-vs14.bat
#   - call %ENVFILESDIR%\eigen-3.1.2-vs12-x64.bat
#   - call %ENVFILESDIR%\glut-2.8.1.bat
#   - call %ENVFILESDIR%\glew-2.1.0.bat
#   - call %ENVFILESDIR%\glm.bat
#   - call %ENVFILESDIR%\HDF5-1.8.17-vs12-x64.bat
#   - call %ENVFILESDIR%\zeromq-4.2.1-vs14-x64
#   - set BUILD_GENERATOR=Visual Studio 14 Win64
#   - set CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON -DCMAKE_POLICY_DEFAULT_CMP0074=NEW
#   - '"c:\Program Files\Git\bin\bash.exe" --login  .gitlab-ci.sh'
#  tags:
#   - win7
