stages:
 - build

Ubuntu-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS=-DVISIMPL_OPTIONALS_AS_REQUIRED=ON
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Ninja"
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

Ubuntu-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export BUILD_GENERATOR="Ninja";
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

OSX-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - module load Qt-5.4
  - export CMAKE_EXTRA_ARGS=-DVISIMPL_OPTIONALS_AS_REQUIRED=ON
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Ninja"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx

OSX-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - module load Qt-5.4
  - export BUILD_GENERATOR="Ninja";
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx

Win7:
 stage: build
 script:
  - call %ENVFILESDIR%\Boost-1.56-vs12-x64.bat
  - call %ENVFILESDIR%\Qt-5.4.bat
  - set JAMBS_TARGETS=eigen
  - set BUILD_GENERATOR=Visual Studio 12 Win64
  - set PATH=%PATH%;"c:\\Program Files (x86)\\Git\\bin"
  - bash.exe --login .gitlab-ci.sh
 tags:
  - win7
